# Generated by Django 5.0.9 on 2025-02-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddToCart',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
