# Generated by Django 5.0.9 on 2025-01-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
