# Generated by Django 5.0.9 on 2025-02-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_checkout_user_remove_purchasehistory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_name',
        ),
    ]
