# Generated by Django 5.0.9 on 2025-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_wishlistitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
