# Generated by Django 5.0.9 on 2025-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_balance_delete_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='upload/user/images/avatar.png', upload_to='upload/user/images/'),
        ),
    ]
