# Generated by Django 5.0.9 on 2025-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='product_price',
        ),
    ]
