# Generated by Django 5.0.9 on 2025-01-06 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
        ('user_profile', '0002_alter_deposit_user_alter_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishlistItem',
        ),
    ]
