# Generated by Django 5.0.9 on 2025-01-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_purchasehistory_quantity_addtocart_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_profile/upload/images/avatar.jpg', upload_to='user_profile/upload/images/'),
        ),
    ]
