# Generated by Django 5.0.9 on 2025-01-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_addtocart_product_name_addtocart_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product_stock',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_stock',
        ),
    ]
